name: mdet
channels:
  - conda-forge
dependencies:
  - python
  - pytorch==2.0.1
  - torchvision==0.15.2
  - pandas
  - omegaconf
  - tqdm
  - opencv
  - humanfriendly
  - ca-certificates
  - certifi
  - openssl
  - matplotlib
  - jsonpickle
  - seaborn
  - ultralytics
  - Pillow
  - cudnn
  